[package]
name = "firmware"
version = "0.1.0"
authors = ["Janosch Gräf <janosch.graef@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "firmware"
test = false
bench = false

[dependencies]
crc = "3.4.0"
embedded-hal = "1.0"
embedded-io = "0.7"
heapless = "0.9.3"
nb = "1.1.0"
postcard = { version = "1.1.3", default-features = false, features = [
    "heapless",
] }
serde = { version = "1.0.229", default-features = false }
ufmt = "0.2.0"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
features = ["arduino-uno"]

[dependencies.avr-device]
version = "0.8.1"

[dependencies.protocol]
path = "../protocol"
features = ["ufmt"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
